config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :projects
  root 'intro#home'
  get 'home',      to: 'intro#home',      as: 'home'
  get 'about',     to: 'intro#about',     as: 'about'
  get 'features',  to: 'intro#features',  as: 'features'
  get 'contact',   to: 'intro#contact',   as: 'contact'
  resources :users
  get 'login',     to: 'session#new',     as: 'login'
  post 'login',    to: 'session#create',  as: 'logging'
  delete 'logout', to: 'session#destroy', as: 'logout'
  get 'office/home'
  get 'office/newClient'
  post 'office/createClient'
  get 'office/clients'
  get 'office/calendar'
end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
  before_action :check_login, only: :home

  def home
  end

  def about
  end

  def features
  end

  def contact
  end
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/views/intro/about.html.haml
= provide(:title, "About | ")
%h1 About
%p This is my idea to optimize and improve law office management.

app/views/intro/contact.html.haml
= provide(:title, "Contact | ")
%h1 Contact
%p If you want to contact write to us!

app/views/intro/features.html.haml
= provide(:title, "Features | ")
%h1 Features
%p This is awesome features!

app/views/intro/home.html.haml
= provide(:title, "Home | ")
%div{:class => "jumbotron jumbotron-fluid"}
  = image_tag("paragraph.png", height: '500', width: '500', class: "paragraph-1")
  = image_tag("paragraph.png", height: '500', width: '500', class: "paragraph-2")
  .container
    %div{:class => "welcome-page"}
      %h1 Law Your Life
      %p Website to manage effectively law office
      %strong= link_to "Sign up!", new_user_path, class: "styled-btn"
      %strong= link_to "Log in!", login_path, class: "styled-btn"