config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :projects
  root 'intro#home'
  get 'home',      to: 'intro#home',      as: 'home'
  get 'about',     to: 'intro#about',     as: 'about'
  get 'features',  to: 'intro#features',  as: 'features'
  get 'contact',   to: 'intro#contact',   as: 'contact'
  resources :users
  get 'login',     to: 'session#new',     as: 'login'
  post 'login',    to: 'session#create',  as: 'logging'
  delete 'logout', to: 'session#destroy', as: 'logout'
  get 'office/home'
  get 'office/newClient'
  post 'office/createClient'
  get 'office/clients'
  get 'office/calendar'
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :check_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to office_home_url
      flash[:notice] = "Welcome!"
    else
      flash[:error] = "Invalid email and/or password"
      render "new"
    end
  end

  def destroy
    log_out if logged_in
    redirect_to root_url
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session[:user_id] = nil
  end

  def logged_in
    !session[:user_id].nil?
  end
end

app/views/session/new.html.haml
= provide(:title, "Log in | ")
%div{:class => "jumbotron jumbotron-fluid"}
  = image_tag("paragraph.png", height: '500', width: '500', class: "paragraph-1")
  = image_tag("paragraph.png", height: '500', width: '500', class: "paragraph-2")
  .container
    %div{:class => "welcome-page"}
      %h2
        Log in
      %div
        = form_for(:session, url: logging_path) do |f|
          %div
            = f.label :email
            = f.email_field :email
          %div
            = f.label :password
            = f.password_field :password
          = f.submit "Log in", class: "btn btn-primary styled-btn"
        %p
          If you don't have an account
          = link_to "sign up", new_user_path
        - flash.each do |key, value|
          %div{:class => "errors"}
            = value