config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :projects
  root 'intro#home'
  get 'home',      to: 'intro#home',      as: 'home'
  get 'about',     to: 'intro#about',     as: 'about'
  get 'features',  to: 'intro#features',  as: 'features'
  get 'contact',   to: 'intro#contact',   as: 'contact'
  resources :users
  get 'login',     to: 'session#new',     as: 'login'
  post 'login',    to: 'session#create',  as: 'logging'
  delete 'logout', to: 'session#destroy', as: 'logout'
  get 'office/home'
  get 'office/newClient'
  post 'office/createClient'
  get 'office/clients'
  get 'office/calendar'
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title,       presence: true
  validates :description, presence: true
  has_many :todos, dependent: :destroy
  accepts_nested_attributes_for :todos, allow_destroy: true
  belongs_to :user, optional: true,
                    inverse_of: :projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsHelper
  before_action :check_user, :require_login
  before_action :set_projects, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(user_id: @id)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project.todos
    @todo = Todo.new
  end

  # GET /projects/new
  def new
    @project = Project.new
    3.times do
      @project.todos.build
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.create(project_params)
      if @project.save
        redirect_to project_path(@project)
      else
        render 'new'
      end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projects
      @project = Project.where(id: params[:id], user_id: @id).first
      if @project.nil?
        redirect_to projects_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project][:user_id] = current_user.id
      params.require(:project).permit(:title, :description, :user_id, :due_date, todos_attributes: [:id, :status, :description, :due_date])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def check_user
    if current_user.admin_id.nil?
      @id = current_user.id
    else
      @id = current_user.admin_id
    end
  end
end

app/views/projects/_form.html.haml
= form_with(model: project, local: true) do |form|
  - if project.errors.any?
    #error_explanation
      %h2
        = pluralize(project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - project.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :description
    = form.text_area :description
  .field
    = form.label :due_date
    = form.datetime_select :due_date
  = form.fields_for :todos do |build|
    .field
      = build.label :description
      = build.text_area :description
    .field
      = build.label :due_date
      = build.datetime_select :due_date
  .actions
    = form.submit

app/views/projects/edit.html.haml
.projects
  %h1 Editing projects
  = render 'form', project: @project
  = link_to 'Show', @project
  = link_to 'Back', :back

app/views/projects/index.html.haml
.projects
  %p#notice= notice
  %h1 Projects
  %table
    %thead
      %tr
        %th Title
        %th Description
        %th Due date
        %th{:colspan => "3"}
    %tbody
      - @projects.each do |project|
        %tr
          %td= project.title
          %td= project.description
          %td= project.due_date
          %td= link_to 'Show', project
          %td= link_to 'Edit', edit_project_path(project)
          %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }
  = link_to 'New Project', new_project_path

app/views/projects/new.html.haml
.projects
  %h1 New Project
  = render 'form', project: @project
  = link_to 'Back', projects_path

app/views/projects/show.html.haml
.projects
  %p#notice= notice
  %p
    %strong Title:
    = @project.title
  %p
    %strong Description:
    = @project.description
  %p
    %strong Due date:
    = @project.due_date
  = link_to 'Edit', edit_project_path(@project)
  = link_to 'Back', projects_path
  .index-todo
    %h3 To Do
    %table
      %thead
        %tr
          %th Status
          %th Description
          %th Due time
          %th{:colspan => "3"}
      %tbody
        - @project.todos.each do |todo|
          %tr
            %td= todo.status
            %td= todo.description
            %td= todo.due_date
            %td= link_to 'Show', todo
            %td= link_to 'Edit', edit_todo_path(todo)
            %td= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }
    = render 'todos/form', project: @todo