config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :projects
  root 'intro#home'
  get 'home',      to: 'intro#home',      as: 'home'
  get 'about',     to: 'intro#about',     as: 'about'
  get 'features',  to: 'intro#features',  as: 'features'
  get 'contact',   to: 'intro#contact',   as: 'contact'
  resources :users
  get 'login',     to: 'session#new',     as: 'login'
  post 'login',    to: 'session#create',  as: 'logging'
  delete 'logout', to: 'session#destroy', as: 'logout'
  get 'office/home'
  get 'office/newClient'
  post 'office/createClient'
  get 'office/clients'
  get 'office/calendar'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  private

  def require_login
    unless logged_in
      redirect_to login_url
    end
  end

  def check_login
    if logged_in
      redirect_to office_home_url
    end
  end

  def only_admin
    unless logged_in && current_user.role == "admin"
      redirect_to office_home_url
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.haml
%div{:class => "header"}
  %h1 Law Your Life
  %p
    Logged in as
    = current_user.email
    |  
    = link_to "Log out", logout_path, method: :delete

app/views/application/_sidebar.html.haml
.sidebar
  .calendar-btn-sidebar
    %span{:class => "glyphicon glyphicon-calendar", :aria-hidden => "true"}
    = link_to "Calendar", office_calendar_path
  .projects-btn-sidebar
    %span{:class => "glyphicon glyphicon-list-alt", :aria-hidden => "true"}
    = link_to "Projects", projects_path
  .invoices-btn-sidebar
    %span{:class => "glyphicon glyphicon-credit-card", :aria-hidden => "true"}
    = link_to "Invoices", root_url
  - if can? :manage, :all
    .generator-btn-sidebar
      %span{:class => "glyphicon glyphicon-folder-open", :aria-hidden => "true"}
      = link_to "Document generator", root_url
    .clients-btn-sidebar
      %span{:class => "glyphicon glyphicon-user", :aria-hidden => "true"}
      = link_to "Clients", office_clients_path
    .create-client-btn-sidebar
      %span{:class => "glyphicon glyphicon-plus", :aria-hidden => "true"}
      = link_to "Create client", office_newClient_path